/**
 * Centralized Supabase Database Schema & Column Mapping Registry
 * 
 * Provides a single source of truth for:
 * 1. Table names
 * 2. Column names & aliases
 * 3. Unused Supabase columns inventory
 * 4. Helper mappers to translate between DB rows and Frontend objects
 */

export const TABLES = {
  LEADS_TO_ORDER: 'leads_to_order',
  ENQUIRY_TO_ORDER: 'enquiry_to_order',
  LEADS_TRACKER: 'leads_tracker',
  ENQUIRY_TRACKER: 'enquiry_tracker',
  CLIENT_MASTER: 'client_master',
  SC_MANAGEMENT: 'SC_management',
  DROPDOWN: 'dropdown',
  MAKE_QUOTATION: 'Make_Quotation',
  QUOTATION_IMAGE: 'quotation_image',
  LOGIN: 'login',
  TANKHWA_PATRA: 'tankhwa_patra',
  TOTAL_VISIT: 'total_visit',
} as const;

export const COLUMNS = {
  [TABLES.LEADS_TO_ORDER]: {
    ID: 'id',
    TIMESTAMP: 'Timestamp',
    LEAD_NO: 'LD-Lead-No',
    RECEIVER_NAME: 'Lead_Receiver_Name',
    SOURCE: 'Lead_Source',
    COMPANY_NAME: 'Company_Name',
    PHONE_NUMBER: 'Phone_Number',
    SALESPERSON_NAME: 'Salesperson_Name',
    LOCATION: 'Location',
    EMAIL: 'Email_Address',
    STATE: 'State',
    ADDRESS: 'Address',
    PERSON_1: 'Person_name_1',
    DESIGNATION_1: 'Designation_1',
    PHONE_1: 'Phone_Number_1',
    PERSON_2: 'Person_Name_2',
    DESIGNATION_2: 'Designation_2',
    PHONE_2: 'Phone_Number_2',
    PERSON_3: 'Person_Name_3',
    DESIGNATION_3: 'Designation_3',
    PHONE_3: 'Phone_Number_3',
    NOB: 'NOB',
    GST_NUMBER: 'GST_Number',
    ADDITIONAL_NOTES: 'Additional_Notes',
    STATUS: 'Status',
    CUSTOMER_SAY: 'What_Did_The_Customer say?',
    ENQUIRY_STATUS: 'Enquiry_Status',
    ENQUIRY_RECEIVED_STATUS: 'Enquiry_Received_Status',
    ENQUIRY_RECEIVED_DATE: 'Enquiry_Received_Date',
    ENQUIRY_FOR_STATE: 'Enquiry_for_State',
    PROJECT_NAME: 'Project_Name',
    ENQUIRY_TYPE: 'Enquiry_Type',
    ENQUIRY_APPROACH: 'Enquiry_Approach',
    PROJECT_APPROX_VALUE: 'Project_Approximate_Value',
    NEXT_ACTION: 'Next_Action',
    NEXT_CALL_DATE: 'Next_Call_Date',
    NEXT_CALL_TIME: 'Next_Call_Time',
    CURRENT_STAGE: 'Current_Stage',
    SEND_QUOTATION_NO: 'Send_Quotation_No.',
    QUOTATION_SHARED_BY: 'Quotation_Shared_By',
    QUOTATION_NUMBER: 'Quotation_Number',
    QUOTATION_VALUE_WITHOUT_TAX: 'Quotation_Value_Without_Tax',
    QUOTATION_VALUE_WITH_TAX: 'Quotation_Value_With_Tax',
    QUOTATION_UPLOAD: 'Quotation_Upload',
    QUOTATION_REMARKS: 'Quotation_Remarks',
    QUOTATION_VALIDATOR_NAME: 'Quotation_Validator_Name',
    QUOTATION_SEND_STATUS: 'Quotation_Send_Status',
    QUOTATION_VALIDATION_REMARK: 'Quotation_Validation_Remark',
    SEND_FAQ_VIDEO: 'Send_FAQ_Video',
    SEND_PRODUCT_VIDEO: 'Send_Product_Video',
    SEND_OFFER_VIDEO: 'Send_Offer_Video',
    SEND_PRODUCT_CATALOG: 'Send_Product_Catalog',
    SEND_PRODUCT_IMAGE: 'Send_Product_Image',
    IS_ORDER_RECEIVED_STATUS: 'Is_Order_Received?_Status',
    ACCEPTANCE_VIA: 'Acceptance_Via',
    PAYMENT_MODE: 'Payment_Mode',
    PAYMENT_TERMS_DAYS: 'Payment_Terms _In_Days',
    OFFER: 'Offer',
    ACCEPTANCE_FILE_UPLOAD: 'Acceptance_File_Upload',
    REMARK: 'REMARK',
    ORDER_LOST_APOLOGY_VIDEO: 'Order_Lost_Apology_Video',
    IF_NO_REASON_STATUS: 'If_No_Then_Get_Relevant_Reason_Status',
    IF_NO_REASON_REMARK: 'If_No_Then_Get_Relevant_Reason_Remark',
    HOLD_REASON_CATEGORY: 'CUSTOMER_ORDER_HOLD_REASON_CATEGORY',
    HOLDING_DATE: 'HOLDING_DATE',
    HOLD_REMARK: 'HOLD_REMARK',
    SC_NAME: 'SC_Name',
    CALLING_DAYS: 'Calling_Days',
    LEADS_TRACKING_STATUS: 'Leads_Tracking_Status',
    ORDER_NO: 'Order_No',
    TRANSPORT_MODE: 'Transport_Mode',
    CONVEYED_FOR_REGISTRATION: 'CONVEYED_FOR_REGISTRATION_FORM',
    TOTAL_ORDER_QTY: 'Total Order Qty',
    ITEM_QTY: 'Item/qty',
    AMOUNT_WITH_TAX: 'Amount With Tax',
    DESTINATION: 'Destination',
    PO_NUMBER: 'Po Number',
    SALES_TYPE: 'Sales_Type',
    HANDLE_PERSON: 'handle_person',
    APPROVED_BY: 'approved_by',
  },

  [TABLES.ENQUIRY_TO_ORDER]: {
    ID: 'id',
    TIMESTAMP: 'timestamp',
    ENQUIRY_NO: 'enquiry_no',
    LEAD_SOURCE: 'lead_source',
    COMPANY_NAME: 'company_name',
    PHONE_NUMBER: 'phone_number',
    SALES_PERSON_NAME: 'sales_person_name',
    LOCATION: 'location',
    EMAIL: 'email',
    SHIPPING_ADDRESS: 'shipping_address',
    ENQUIRY_RECEIVER_NAME: 'enquiry_receiver_name',
    ENQUIRY_ASSIGN_TO_PROJECT: 'enquiry_assign_to_project',
    GST_NUMBER: 'gst_number',
    ENQUIRY_DATE: 'enquiry_date',
    ENQUIRY_FOR_STATE: 'enquiry_for_state',
    PROJECT_NAME: 'project_name',
    SALES_TYPE: 'sales_type',
    ENQUIRY_APPROACH: 'enquiry_approach',
    ENQUIRY_STATUS: 'enquiry_status',
    CUSTOMER_FEEDBACK: 'customer_feedback',
    CURRENT_STAGE: 'current_stage',
    SEND_QUOTATION_NO: 'send_quotation_no',
    QUOTATION_SHARED_BY: 'quotation_shared_by',
    QUOTATION_NUMBER: 'quotation_number',
    QUOTATION_VALUE_WITHOUT_TAX: 'quotation_value_without_tax',
    QUOTATION_VALUE_WITH_TAX: 'quotation_value_with_tax',
    QUOTATION_UPLOAD: 'quotation_upload',
    QUOTATION_REMARKS: 'quotation_remarks',
    QUOTATION_VALIDATOR_NAME: 'quotation_validator_name',
    QUOTATION_SEND_STATUS: 'quotation_send_status',
    QUOTATION_VALIDATION_REMARK: 'quotation_validation_remark',
    SEND_FAQ_VIDEO: 'send_faq_video',
    SEND_PRODUCT_VIDEO: 'send_product_video',
    SEND_OFFER_VIDEO: 'send_offer_video',
    SEND_PRODUCT_CATALOG: 'send_product_catalog',
    SEND_PRODUCT_IMAGE: 'send_product_image',
    NEXT_CALL_DATE: 'next_call_date',
    NEXT_CALL_TIME: 'next_call_time',
    IS_ORDER_RECEIVED_STATUS: 'is_order_received_status',
    ACCEPTANCE_VIA: 'acceptance_via',
    PAYMENT_MODE: 'payment_mode',
    PAYMENT_TERMS_DAYS: 'payment_terms_days',
    OFFER: 'offer',
    ACCEPTANCE_FILE_UPLOAD: 'acceptance_file_upload',
    REMARK: 'remark',
    ORDER_LOST_APOLOGY_VIDEO: 'order_lost_apology_video',
    IF_NO_REASON_STATUS: 'if_no_reason_status',
    IF_NO_REASON_REMARK: 'if_no_reason_remark',
    HOLD_REASON_CATEGORY: 'customer_order_hold_reason_category',
    HOLDING_DATE: 'holding_date',
    HOLD_REMARK: 'hold_remark',
    TRANSPORT_MODE: 'transport_mode',
    CONVEYED_FOR_REGISTRATION: 'conveyed_for_registration_form',
    SALES_COORDINATOR_NAME: 'sales_coordinator_name',
    CALLING_DAYS: 'calling_days',
    ORDER_NO: 'order_no',
    AMOUNT_WITH_GST: 'amount_with_gst',
    ITEM_QTY: 'item_qty',
    TOTAL_QTY: 'total_qty',
    DESTINATION: 'destination',
    PO_NUMBER: 'po_number',
    CREATED_AT: 'created_at',
    APPROVED_BY: 'approved_by',
  },

  [TABLES.CLIENT_MASTER]: {
    UUID: 'uuid',
    CREATED_AT: 'created_at',
    COMPANY_NAME: 'company_name',
    CLIENT_NAME: 'client_name',
    CLIENT_MOBILE_NUMBER: 'client_mobile_number',
    STATE: 'state',
    BILLING_ADDRESS: 'billing_address',
    GST_NUMBER: 'gst_number',
    COMPANY_GROUP_NAME: 'company_group_name',
    SC_NAME: 'sc_name',
    CRM_NAME: 'crm_name',
    STATE_CODE: 'state_code',
    CREDIT_DAYS: 'credit_days',
    CREDIT_LIMIT: 'credit_limit',
    UPDATED_AT: 'updated_at',
    CLIENT_CODE: 'client_code',
    IS_RELEVANT: 'isRelevant',
  },

  [TABLES.SC_MANAGEMENT]: {
    UUID: 'uuid',
    KEY: 'key',
    VALUE: 'value',
    CATEGORY: 'category',
    IS_ACTIVE: 'isActive',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },

  [TABLES.LOGIN]: {
    ID: 'id',
    USERNAME: 'username',
    PASSWORD: 'password',
    CREATED_AT: 'created_at',
    USERTYPE: 'usertype',
    ALTERNATE_ACCESS: 'alternate_access',
  },

  [TABLES.DROPDOWN]: {
    ID: 'id',
    LEAD_RECEIVER_NAME: 'lead_receiver_name',
    LEAD_SOURCE: 'lead_source',
    STATE: 'state',
    SALES_TYPE: 'sales_type',
    SC_NAME: 'sc_name',
    ITEM_NAME: 'item_name',
    ITEM_CODE: 'item_code',
    ITEM_CATEGORY: 'item_category',
    RATE: 'rate',
    DESCRIPTION: 'description',
    NOB: 'nob',
    ENQUIRY_APPROACH: 'enquiry_approach',
    ENQUIRY_RECEIVER_NAME: 'enquiry_receiver_name',
    ENQUIRY_ASSIGN_TO: 'enquiry_assign_to',
    SALES_COORDINATOR_NAME: 'sales_co_ordinator_name',
  },

  [TABLES.MAKE_QUOTATION]: {
    ID: 'id',
    TIMESTAMP: 'Timestamp',
    QUOTATION_NO: 'Quotation_No',
    QUOTATION_DATE: 'Quotation_Date',
    PREPARED_BY: 'Prepared_By',
    COMPANY_NAME: 'Company_Name',
    GRAND_TOTAL: 'Grand_Total',
    ITEMS: 'Items',
    PDF_URL: 'Pdf_Url',
  },
} as const;

/**
 * Inventory of columns present in Supabase schema but unused in frontend
 */
export const UNUSED_COLUMNS = {
  [TABLES.LEADS_TO_ORDER]: [
    'Planned', 'Actual', 'Delay',
    'Planned1', 'Actual1', 'Delay1',
    'Credit _Access', 'Credit_Days', 'Credit_Limit',
    'Customer_Registration Form', 'timestamp_text_backup',
    'Next Call Date_1', 'Next Call Time_1', 'Calling Days_1'
  ],
  [TABLES.ENQUIRY_TO_ORDER]: [
    'planned1', 'actual1', 'delay1',
    'item_name6', 'quantity6', 'item_name7', 'quantity7',
    'item_name8', 'quantity8', 'item_name9', 'quantity9',
    'item_name10', 'quantity10'
  ],
  [TABLES.DROPDOWN]: [
    'consignee_tax_percent', 'sp_details_reference_name', 'sp_contact_no',
    'sp_state', 'sp_state_code', 'sp_pan', 'quotation_consignor_state',
    'quotation_consignor_data', 'quotation_consignor_address',
    'quotation_consignor_gstin_statecode', 'quotation_consignor_state_code',
    'quotation_consignor_gstin', 'quotation_consignor_gstin_address_pin',
    'quotation_consignor_msmeno', 'direct_enquiry_cre_name',
    'direct_enquiry_client_type', 'direct_enquiry_credit_amount',
    'direct_enquiry_credit_days', 'requirment_product_category_codes', 'pass'
  ],
  [TABLES.MAKE_QUOTATION]: [
    'Divine_Empire_10th_Anniversary_Special_Offer'
  ],
  [TABLES.TANKHWA_PATRA]: [
    'Customize Fields', 'Report Customize Fields'
  ]
} as const;

/**
 * Helper mapper: Converts DB row from `leads_to_order` to frontend object
 */
export function mapLeadRowFromDB(row: Record<string, any>) {
  if (!row) return null;
  return {
    id: row.id,
    timestamp: row['Timestamp'] || row.date,
    leadNumber: row['LD-Lead-No'],
    receiverName: row['Lead_Receiver_Name'],
    source: row['Lead_Source'],
    companyName: row['Company_Name'],
    phoneNumber: row['Phone_Number'],
    salespersonName: row['Salesperson_Name'],
    location: row['Location'],
    email: row['Email_Address'],
    state: row['State'],
    address: row['Address'],
    person1Name: row['Person_name_1'],
    person1Designation: row['Designation_1'],
    person1Phone: row['Phone_Number_1'],
    person2Name: row['Person_Name_2'],
    person2Designation: row['Designation_2'],
    person2Phone: row['Phone_Number_2'],
    person3Name: row['Person_Name_3'],
    person3Designation: row['Designation_3'],
    person3Phone: row['Phone_Number_3'],
    nob: row['NOB'],
    gstNumber: row['GST_Number'],
    additionalNotes: row['Additional_Notes'],
    status: row['Status'],
    salesType: row['Sales_Type'],
    handlePerson: row['handle_person'],
    approvedBy: row['approved_by'],
  };
}

/**
 * Helper mapper: Converts frontend Lead object to `leads_to_order` DB row
 */
export function mapLeadToDBRow(lead: Record<string, any>) {
  return {
    'Timestamp': lead.timestamp || new Date().toLocaleDateString('en-GB') + ' ' + new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
    'LD-Lead-No': lead.leadNumber,
    'Lead_Receiver_Name': lead.receiverName || '',
    'Lead_Source': lead.source || '',
    'Company_Name': lead.companyName || '',
    'Phone_Number': lead.phoneNumber || '',
    'Salesperson_Name': lead.salespersonName || '',
    'Location': lead.location || '',
    'Email_Address': lead.email || '',
    'State': lead.state || '',
    'Address': lead.address || '',
    'Person_name_1': lead.person1Name || '',
    'Designation_1': lead.person1Designation || '',
    'Phone_Number_1': lead.person1Phone || '',
    'Person_Name_2': lead.person2Name || '',
    'Designation_2': lead.person2Designation || '',
    'Phone_Number_2': lead.person2Phone || '',
    'Person_Name_3': lead.person3Name || '',
    'Designation_3': lead.person3Designation || '',
    'Phone_Number_3': lead.person3Phone || '',
    'NOB': lead.nob || '',
    'GST_Number': lead.gstNumber || '',
    'Additional_Notes': lead.additionalNotes || '',
    'Status': lead.status || 'Pending',
    'Sales_Type': lead.salesType || '',
    'handle_person': lead.handlePerson || '',
    'approved_by': lead.approvedBy || '',
  };
}
